# Generated by Django 4.2 on 2023-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0002_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='surprise',
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
