# Generated by Django 4.2 on 2023-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0004_remove_movie_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_rating',
        ),
    ]
