# Generated by Django 4.2 on 2023-05-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0005_remove_movie_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='metascore',
        ),
    ]
