# Generated by Django 4.2 on 2023-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0007_alter_movie_sad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
