# Generated by Django 4.2 on 2023-05-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0011_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
