# Generated by Django 4.2 on 2023-05-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0013_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecustomuser',
            options={'verbose_name_plural': 'User'},
        ),
    ]
