# Generated by Django 4.2 on 2023-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0014_alter_moviecustomuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieuser', models.IntegerField()),
                ('selected_movies', models.CharField(max_length=100)),
            ],
        ),
    ]
