# Generated by Django 4.2 on 2023-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendationapp', '0017_remove_movieselection_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieselection',
            name='imdbid',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
